import mongoose from "mongoose";
import Restaurant from "../models/RestaurantModel.js";
import MenuItem from "../models/MenuItemModel.js";

mongoose.connect("mongodb://localhost:27017/DineSmart", {
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on("error", console.error.bind(console, "connection error:"));
db.once("open", async () => {
  console.log("Connected to MongoDB");

  try {
    // Clear existing data
    await Restaurant.deleteMany({});
    await MenuItem.deleteMany({});

    const restaurant1 = await Restaurant.create({
      name: "Spicy Garden",
      description: "Authentic Indian Cuisine",
      address: "123 MG Road, Bengaluru",
      location: {
        type: "Point",
        coordinates: [77.5946, 12.9716], // [longitude, latitude]
      },
      image: "https://example.com/spicy-garden.jpg",
      cuisine: "Indian",
      tags: ["spicy", "veg", "family"],
      deliveryTime: 30,
      rating: 4.5,
      priceRange: "₹₹",
      isVeg: true,
      featured: true,
      contactInfo: {
        phone: "+91 9876543210",
        email: "info@spicygarden.in",
        hours: ["10am - 10pm"],
        manager: "Rajesh Kumar",
        emergencyContact: "+91 9123456789",
      },
    });

    const restaurant2 = await Restaurant.create({
      name: "Mumbai Street Food",
      description: "Authentic Mumbai street food flavors in a hygienic setting",
      address: "202 Chowpatty Lane, Westside",
      location: {
        type: "Point",
        coordinates: [72.8258, 18.975],
      },
      image: "https://example.com/mumbaistreet.jpg",
      cuisine: "Indian",
      tags: ["street food", "quick bites", "budget-friendly"],
      deliveryTime: 25,
      rating: 4.3,
      priceRange: "$",
      isVeg: false,
      featured: false,
      contactInfo: {
        phone: "555-2222",
        email: "hello@mumbaistreet.com",
        hours: ["10:00 AM - 12:00 AM", "Open 7 days"],
        manager: "Priya Desai",
        emergencyContact: "555-9222",
      },
    });

    const restaurant3 = await Restaurant.create({
      name: "Punjab Grill",
      description: "Hearty North Indian cuisine with robust flavors",
      address: "303 Tandoor Circle, North District",
      location: {
        type: "Point",
        coordinates: [77.1025, 28.7041],
      },
      image: "https://example.com/punjabgrill.jpg",
      cuisine: "Indian",
      tags: ["tandoori", "butter chicken", "naan"],
      deliveryTime: 38,
      rating: 4.6,
      priceRange: "$$$",
      isVeg: false,
      featured: true,
      contactInfo: {
        phone: "555-3333",
        email: "info@punjabgrill.com",
        hours: ["11:00 AM - 11:30 PM", "Open 7 days"],
        manager: "Harpreet Kaur",
        emergencyContact: "555-9333",
      },
    });

    const restaurant4 = await Restaurant.create({
      name: "Southern Spice",
      description: "Authentic South Indian vegetarian cuisine",
      address: "404 Dosa Plaza, Eastside",
      location: {
        type: "Point",
        coordinates: [80.2707, 13.0827], // Chennai coordinates
      },
      image: "https://example.com/southernspice.jpg",
      cuisine: "Indian",
      tags: ["vegetarian", "dosa", "idli", "sambar"],
      deliveryTime: 33, // Average of 25-40 mins
      rating: 4.4,
      priceRange: "$$",
      isVeg: true,
      featured: false,
      contactInfo: {
        phone: "555-4444",
        email: "contact@southernspice.com",
        hours: ["7:00 AM - 10:30 PM", "Closed on Wednesdays"],
        manager: "Arun Kumar",
        emergencyContact: "555-9444",
      },
    });

    const restaurant5 = await Restaurant.create({
      name: "Kolkata Kathi Roll",
      description: "Specializing in authentic Kolkata-style kathi rolls",
      address: "505 Roll Street, Central",
      location: {
        type: "Point",
        coordinates: [88.3639, 22.5726], // Kolkata coordinates
      },
      image: "https://example.com/kathiroll.jpg",
      cuisine: "Indian",
      tags: ["quick service", "rolls", "egg dishes"],
      deliveryTime: 20, // Average of 15-25 mins
      rating: 4.2,
      priceRange: "$",
      isVeg: false,
      featured: false,
      contactInfo: {
        phone: "555-5555",
        email: "orders@kathiroll.com",
        hours: ["9:00 AM - 1:00 AM", "Open 7 days"],
        manager: "Rahul Banerjee",
        emergencyContact: "555-9555",
      },
    });

    const restaurant6 = await Restaurant.create({
      name: "Gujarat Thali",
      description: "Unlimited Gujarati thali with traditional flavors",
      address: "606 Thali Road, Southside",
      location: {
        type: "Point",
        coordinates: [72.5714, 23.0225], // Ahmedabad coordinates
      },
      image: "https://example.com/gujaratthali.jpg",
      cuisine: "Indian",
      tags: ["thali", "vegetarian", "unlimited"],
      deliveryTime: 43, // Average of 35-50 mins
      rating: 4.5,
      priceRange: "$$",
      isVeg: true,
      featured: true,
      contactInfo: {
        phone: "555-6666",
        email: "thali@gujaratthali.com",
        hours: ["11:30 AM - 3:30 PM, 6:30 PM - 10:30 PM", "Closed on Mondays"],
        manager: "Meena Patel",
        emergencyContact: "555-9666",
      },
    });

    // Menu Items for Royal Spice
    await MenuItem.create([
      {
        name: "Nawabi Biryani",
        description: "Hyderabadi dum biryani with 24-hour marinated lamb",
        price: 22.99,
        image: "https://example.com/nawabibiryani.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["basmati rice", "lamb", "yogurt", "saffron", "spices"],
        nutritionInfo: {
          calories: 780,
          protein: 42,
          carbs: 85,
          fat: 32,
          fiber: 5,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant1._id,
        reviews: [
          {
            user: "FoodExplorer123",
            rating: 5,
            comment: "The best biryani I've had outside Hyderabad!",
            date: new Date("2023-05-15"),
          },
          {
            user: "SpiceLover",
            rating: 4,
            comment: "Authentic flavors but slightly pricey",
            date: new Date("2023-06-02"),
          },
        ],
      },
      {
        name: "Murgh Malai Kebab",
        description:
          "Creamy chicken kebabs marinated in cheese and mild spices",
        price: 18.99,
        image: "https://example.com/murghmalaikebab.jpg",
        category: "appetizer",
        isVeg: false,
        isSpicy: false,
        ingredients: ["chicken", "cream", "cheese", "cardamom", "coriander"],
        nutritionInfo: {
          calories: 420,
          protein: 38,
          carbs: 8,
          fat: 28,
          fiber: 2,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant1._id,
        reviews: [
          {
            user: "KebabKing",
            rating: 5,
            comment: "Unbelievably tender and flavorful!",
            date: new Date("2023-04-20"),
          },
        ],
      },
      {
        name: "Dal Makhani",
        description: "Slow-cooked black lentils with butter and cream",
        price: 14.99,
        image: "https://example.com/dalmakhani.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: false,
        ingredients: [
          "black lentils",
          "kidney beans",
          "butter",
          "cream",
          "tomato",
        ],
        nutritionInfo: {
          calories: 380,
          protein: 18,
          carbs: 42,
          fat: 18,
          fiber: 15,
        },
        allergenInfo: ["dairy"],
        restaurant: restaurant1._id,
      },
      {
        name: "Paneer Tikka Masala",
        description: "Cottage cheese cubes in rich tomato and cream gravy",
        price: 16.99,
        image: "https://example.com/paneertikka.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["paneer", "tomato", "cream", "capsicum", "onion"],
        nutritionInfo: {
          calories: 450,
          protein: 22,
          carbs: 28,
          fat: 30,
          fiber: 6,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant1._id,
      },
      {
        name: "Tandoori Jhinga",
        description: "Jumbo prawns marinated in yogurt and tandoori spices",
        price: 24.99,
        image: "https://example.com/tandoorijhinga.jpg",
        category: "appetizer",
        isVeg: false,
        isSpicy: true,
        ingredients: [
          "prawns",
          "yogurt",
          "ginger",
          "garlic",
          "tandoori masala",
        ],
        nutritionInfo: {
          calories: 320,
          protein: 36,
          carbs: 8,
          fat: 16,
          fiber: 2,
        },
        allergenInfo: ["shellfish", "dairy"],
        restaurant: restaurant1._id,
      },
      {
        name: "Bharwan Aloo",
        description: "Baby potatoes stuffed with nuts and spices",
        price: 12.99,
        image: "https://example.com/bharwanaloo.jpg",
        category: "appetizer",
        isVeg: true,
        isSpicy: false,
        ingredients: ["potatoes", "cashews", "raisins", "coriander", "spices"],
        nutritionInfo: {
          calories: 280,
          protein: 6,
          carbs: 42,
          fat: 10,
          fiber: 8,
        },
        restaurant: restaurant1._id,
      },
      {
        name: "Rogan Josh",
        description: "Kashmiri lamb curry with aromatic spices",
        price: 20.99,
        image: "https://example.com/roganjosh.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["lamb", "yogurt", "kashmiri chili", "ginger", "fennel"],
        nutritionInfo: {
          calories: 520,
          protein: 40,
          carbs: 18,
          fat: 35,
          fiber: 6,
        },
        allergenInfo: ["dairy"],
        restaurant: restaurant1._id,
      },
      {
        name: "Naan Basket",
        description: "Assortment of 4 different naan breads",
        price: 8.99,
        image: "https://example.com/naanbasket.jpg",
        category: "breads",
        isVeg: true,
        ingredients: ["flour", "yeast", "garlic", "butter", "herbs"],
        nutritionInfo: {
          calories: 320,
          protein: 10,
          carbs: 56,
          fat: 8,
          fiber: 4,
        },
        allergenInfo: ["gluten", "dairy"],
        popular: true,
        restaurant: restaurant1._id,
      },
      {
        name: "Kulfi Falooda",
        description:
          "Traditional Indian ice cream with vermicelli and rose syrup",
        price: 7.99,
        image: "https://example.com/kulfifalooda.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: [
          "milk",
          "sugar",
          "rose syrup",
          "vermicelli",
          "pistachios",
        ],
        nutritionInfo: {
          calories: 380,
          protein: 8,
          carbs: 62,
          fat: 12,
          fiber: 2,
        },
        allergenInfo: ["dairy", "nuts"],
        restaurant: restaurant1._id,
      },
      {
        name: "Masala Chai",
        description: "Spiced Indian tea with cardamom and ginger",
        price: 3.99,
        image: "https://example.com/masalachai.jpg",
        category: "beverage",
        isVeg: true,
        ingredients: ["tea leaves", "milk", "cardamom", "ginger", "sugar"],
        nutritionInfo: {
          calories: 120,
          protein: 4,
          carbs: 18,
          fat: 4,
          fiber: 0,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant1._id,
      },
    ]);

    // Menu Items for Mumbai Street Food
    await MenuItem.create([
      {
        name: "Vada Pav",
        description: "Mumbai's famous potato fritter burger",
        price: 2.99,
        image: "https://example.com/vadapav.jpg",
        category: "snack",
        isVeg: true,
        isSpicy: true,
        ingredients: ["potato", "bread", "chutneys", "spices"],
        nutritionInfo: {
          calories: 280,
          protein: 6,
          carbs: 45,
          fat: 8,
          fiber: 5,
        },
        allergenInfo: ["gluten"],
        popular: true,
        restaurant: restaurant2._id,
        reviews: [
          {
            user: "MumbaiLover",
            rating: 5,
            comment: "Tastes just like what you get at Churchgate station!",
            date: new Date("2023-07-10"),
          },
          {
            user: "BudgetEater",
            rating: 4,
            comment: "Great value for money",
            date: new Date("2023-08-05"),
          },
        ],
      },
      {
        name: "Pani Puri",
        description: "Crisp puris filled with spicy tamarind water",
        price: 4.99,
        image: "https://example.com/panipuri.jpg",
        category: "snack",
        isVeg: true,
        isSpicy: true,
        ingredients: ["puris", "tamarind", "mint", "potato", "chickpeas"],
        nutritionInfo: {
          calories: 180,
          protein: 3,
          carbs: 32,
          fat: 4,
          fiber: 6,
        },
        popular: true,
        restaurant: restaurant2._id,
      },
      {
        name: "Bhel Puri",
        description: "Puffed rice snack with tangy chutneys",
        price: 5.99,
        image: "https://example.com/bhelpuri.jpg",
        category: "snack",
        isVeg: true,
        isSpicy: true,
        ingredients: ["puffed rice", "sev", "onion", "tomato", "chutneys"],
        nutritionInfo: {
          calories: 220,
          protein: 4,
          carbs: 38,
          fat: 6,
          fiber: 4,
        },
        restaurant: restaurant2._id,
      },
      {
        name: "Dabeli",
        description: "Kutchi style spicy potato burger",
        price: 3.99,
        image: "https://example.com/dabeli.jpg",
        category: "snack",
        isVeg: true,
        isSpicy: true,
        ingredients: [
          "potato",
          "bun",
          "dabeli masala",
          "peanuts",
          "pomegranate",
        ],
        nutritionInfo: {
          calories: 320,
          protein: 7,
          carbs: 52,
          fat: 10,
          fiber: 6,
        },
        allergenInfo: ["gluten", "nuts"],
        restaurant: restaurant2._id,
      },
      {
        name: "Misal Pav",
        description: "Spicy sprouted bean curry with bread",
        price: 6.99,
        image: "https://example.com/misalpav.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["sprouts", "gravy", "farsan", "onion", "bread"],
        nutritionInfo: {
          calories: 380,
          protein: 18,
          carbs: 58,
          fat: 12,
          fiber: 15,
        },
        allergenInfo: ["gluten"],
        popular: true,
        restaurant: restaurant2._id,
      },
      {
        name: "Pav Bhaji",
        description: "Buttery mashed vegetable curry with bread",
        price: 7.99,
        image: "https://example.com/pavbhaji.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: [
          "mixed vegetables",
          "butter",
          "pav bhaji masala",
          "bread",
        ],
        nutritionInfo: {
          calories: 420,
          protein: 10,
          carbs: 62,
          fat: 16,
          fiber: 12,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant2._id,
      },
      {
        name: "Kanda Poha",
        description: "Flattened rice with onions and peanuts",
        price: 5.99,
        image: "https://example.com/kandapoha.jpg",
        category: "breakfast",
        isVeg: true,
        isSpicy: false,
        ingredients: ["poha", "onion", "peanuts", "turmeric", "coriander"],
        nutritionInfo: {
          calories: 280,
          protein: 6,
          carbs: 48,
          fat: 8,
          fiber: 4,
        },
        allergenInfo: ["nuts"],
        restaurant: restaurant2._id,
      },
      {
        name: "Sabudana Khichdi",
        description: "Tapioca pearls with peanuts and potatoes",
        price: 6.99,
        image: "https://example.com/sabudana.jpg",
        category: "breakfast",
        isVeg: true,
        isSpicy: false,
        ingredients: ["sabudana", "peanuts", "potato", "cumin", "coconut"],
        nutritionInfo: {
          calories: 320,
          protein: 5,
          carbs: 62,
          fat: 6,
          fiber: 4,
        },
        allergenInfo: ["nuts"],
        restaurant: restaurant2._id,
      },
      {
        name: "Mango Lassi",
        description: "Sweet yogurt drink with mango pulp",
        price: 3.99,
        image: "https://example.com/mangolassi.jpg",
        category: "beverage",
        isVeg: true,
        ingredients: ["yogurt", "mango", "sugar", "cardamom"],
        nutritionInfo: {
          calories: 220,
          protein: 6,
          carbs: 38,
          fat: 5,
          fiber: 2,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant2._id,
      },
      {
        name: "Kala Khatta Gola",
        description: "Shaved ice with blackberry syrup",
        price: 2.99,
        image: "https://example.com/kalakhatta.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: ["ice", "blackberry syrup", "salt", "chili powder"],
        nutritionInfo: {
          calories: 120,
          protein: 0,
          carbs: 30,
          fat: 0,
          fiber: 0,
        },
        restaurant: restaurant2._id,
      },
    ]);

    // Menu Items for Punjab Grill
    await MenuItem.create([
      {
        name: "Amritsari Kulcha",
        description: "Stuffed leavened bread from Amritsar",
        price: 5.99,
        image: "https://example.com/amritsarikulcha.jpg",
        category: "bread",
        isVeg: true,
        isSpicy: false,
        ingredients: ["flour", "potato", "onion", "spices", "butter"],
        nutritionInfo: {
          calories: 320,
          protein: 8,
          carbs: 52,
          fat: 10,
          fiber: 6,
        },
        allergenInfo: ["gluten", "dairy"],
        popular: true,
        restaurant: restaurant3._id,
        reviews: [
          {
            user: "BreadLover",
            rating: 5,
            comment: "Perfectly crisp outside and soft inside!",
            date: new Date("2023-06-18"),
          },
        ],
      },
      {
        name: "Dal Tadka",
        description: "Tempered yellow lentils with ghee",
        price: 9.99,
        image: "https://example.com/daltadka.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["yellow lentils", "tomato", "onion", "ghee", "spices"],
        nutritionInfo: {
          calories: 280,
          protein: 14,
          carbs: 38,
          fat: 8,
          fiber: 12,
        },
        allergenInfo: ["dairy"],
        restaurant: restaurant3._id,
      },
      {
        name: "Chole Bhature",
        description: "Spicy chickpeas with fried bread",
        price: 10.99,
        image: "https://example.com/cholebhature.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["chickpeas", "flour", "yogurt", "onion", "spices"],
        nutritionInfo: {
          calories: 680,
          protein: 18,
          carbs: 85,
          fat: 32,
          fiber: 15,
        },
        allergenInfo: ["gluten"],
        popular: true,
        restaurant: restaurant3._id,
      },
      {
        name: "Tandoori Chicken",
        description:
          "Chicken marinated in yogurt and spices, cooked in tandoor",
        price: 14.99,
        image: "https://example.com/tandoorichicken.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: [
          "chicken",
          "yogurt",
          "ginger",
          "garlic",
          "tandoori masala",
        ],
        nutritionInfo: {
          calories: 320,
          protein: 42,
          carbs: 8,
          fat: 14,
          fiber: 2,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant3._id,
      },
      {
        name: "Sarson Ka Saag",
        description: "Mustard greens cooked with spices",
        price: 11.99,
        image: "https://example.com/sarsonkasaag.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: false,
        ingredients: [
          "mustard greens",
          "spinach",
          "cornmeal",
          "ginger",
          "garlic",
        ],
        nutritionInfo: {
          calories: 180,
          protein: 8,
          carbs: 22,
          fat: 8,
          fiber: 10,
        },
        restaurant: restaurant3._id,
      },
      {
        name: "Makki Di Roti",
        description: "Corn flour flatbread",
        price: 4.99,
        image: "https://example.com/makkidiroti.jpg",
        category: "bread",
        isVeg: true,
        ingredients: ["corn flour", "water", "salt"],
        nutritionInfo: {
          calories: 160,
          protein: 4,
          carbs: 32,
          fat: 2,
          fiber: 4,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant3._id,
      },
      {
        name: "Punjabi Lassi",
        description: "Traditional sweet yogurt drink",
        price: 3.99,
        image: "https://example.com/punjabilassi.jpg",
        category: "beverage",
        isVeg: true,
        ingredients: ["yogurt", "sugar", "cardamom", "rose water"],
        nutritionInfo: {
          calories: 240,
          protein: 8,
          carbs: 32,
          fat: 8,
          fiber: 0,
        },
        allergenInfo: ["dairy"],
        restaurant: restaurant3._id,
      },
      {
        name: "Gajar Ka Halwa",
        description: "Carrot pudding with nuts",
        price: 6.99,
        image: "https://example.com/gajarkahalwa.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: ["carrots", "milk", "sugar", "ghee", "nuts"],
        nutritionInfo: {
          calories: 380,
          protein: 6,
          carbs: 52,
          fat: 18,
          fiber: 6,
        },
        allergenInfo: ["dairy", "nuts"],
        popular: true,
        restaurant: restaurant3._id,
      },
      {
        name: "Rajma Chawal",
        description: "Kidney beans curry with rice",
        price: 10.99,
        image: "https://example.com/rajmachawal.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["kidney beans", "rice", "onion", "tomato", "spices"],
        nutritionInfo: {
          calories: 480,
          protein: 18,
          carbs: 82,
          fat: 8,
          fiber: 18,
        },
        restaurant: restaurant3._id,
      },
      {
        name: "Aloo Paratha",
        description: "Stuffed potato flatbread",
        price: 7.99,
        image: "https://example.com/alooparatha.jpg",
        category: "bread",
        isVeg: true,
        isSpicy: false,
        ingredients: ["flour", "potato", "spices", "butter"],
        nutritionInfo: {
          calories: 360,
          protein: 8,
          carbs: 58,
          fat: 12,
          fiber: 6,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant3._id,
      },
    ]);

    // Menu Items for Southern Spice
    await MenuItem.create([
      {
        name: "Masala Dosa",
        description: "Crispy rice crepe with potato filling",
        price: 8.99,
        image: "https://example.com/masaladosa.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["rice batter", "urad dal", "potato", "onion", "spices"],
        nutritionInfo: {
          calories: 320,
          protein: 8,
          carbs: 58,
          fat: 6,
          fiber: 8,
        },
        allergenInfo: ["gluten-free"],
        popular: true,
        restaurant: restaurant4._id,
        reviews: [
          {
            user: "DosaFanatic",
            rating: 5,
            comment: "Perfectly crisp dosa with flavorful potato filling",
            date: new Date("2023-05-22"),
          },
        ],
      },
      {
        name: "Idli Sambar",
        description: "Steamed rice cakes with lentil stew",
        price: 6.99,
        image: "https://example.com/idlisambar.jpg",
        category: "breakfast",
        isVeg: true,
        isSpicy: true,
        ingredients: ["rice", "urad dal", "toor dal", "vegetables", "spices"],
        nutritionInfo: {
          calories: 220,
          protein: 10,
          carbs: 42,
          fat: 2,
          fiber: 10,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant4._id,
      },
      {
        name: "Vada Sambar",
        description: "Fried lentil donuts with vegetable stew",
        price: 6.99,
        image: "https://example.com/vadasambar.jpg",
        category: "breakfast",
        isVeg: true,
        isSpicy: true,
        ingredients: ["urad dal", "toor dal", "vegetables", "spices", "oil"],
        nutritionInfo: {
          calories: 280,
          protein: 12,
          carbs: 38,
          fat: 10,
          fiber: 8,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant4._id,
      },
      {
        name: "Rava Uttapam",
        description: "Savory semolina pancake with toppings",
        price: 7.99,
        image: "https://example.com/ravauttapam.jpg",
        category: "breakfast",
        isVeg: true,
        isSpicy: false,
        ingredients: ["semolina", "yogurt", "onion", "tomato", "coriander"],
        nutritionInfo: {
          calories: 260,
          protein: 8,
          carbs: 42,
          fat: 6,
          fiber: 4,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant4._id,
      },
      {
        name: "Pongal",
        description: "Rice and lentil porridge with ghee",
        price: 6.99,
        image: "https://example.com/pongal.jpg",
        category: "breakfast",
        isVeg: true,
        isSpicy: false,
        ingredients: ["rice", "moong dal", "pepper", "cumin", "ghee"],
        nutritionInfo: {
          calories: 280,
          protein: 8,
          carbs: 48,
          fat: 6,
          fiber: 6,
        },
        allergenInfo: ["gluten-free", "dairy"],
        restaurant: restaurant4._id,
      },
      {
        name: "Filter Coffee",
        description: "Traditional South Indian filter coffee",
        price: 2.99,
        image: "https://example.com/filtercoffee.jpg",
        category: "beverage",
        isVeg: true,
        ingredients: ["coffee powder", "milk", "sugar"],
        nutritionInfo: {
          calories: 120,
          protein: 4,
          carbs: 18,
          fat: 4,
          fiber: 0,
        },
        allergenInfo: ["dairy"],
        popular: true,
        restaurant: restaurant4._id,
      },
      {
        name: "Bisi Bele Bath",
        description: "Spicy rice dish with lentils and vegetables",
        price: 9.99,
        image: "https://example.com/bisibelebath.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: [
          "rice",
          "toor dal",
          "vegetables",
          "bisi bele bath powder",
          "ghee",
        ],
        nutritionInfo: {
          calories: 380,
          protein: 12,
          carbs: 68,
          fat: 8,
          fiber: 12,
        },
        allergenInfo: ["gluten-free", "dairy"],
        restaurant: restaurant4._id,
      },
      {
        name: "Rasam",
        description: "Pepper-tamarind soup",
        price: 4.99,
        image: "https://example.com/rasam.jpg",
        category: "soup",
        isVeg: true,
        isSpicy: true,
        ingredients: ["tamarind", "pepper", "tomato", "cumin", "coriander"],
        nutritionInfo: {
          calories: 80,
          protein: 2,
          carbs: 18,
          fat: 1,
          fiber: 4,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant4._id,
      },
      {
        name: "Coconut Chutney",
        description: "Fresh coconut dip with lentils",
        price: 2.99,
        image: "https://example.com/coconutchutney.jpg",
        category: "side",
        isVeg: true,
        isSpicy: false,
        ingredients: ["coconut", "chana dal", "green chili", "curry leaves"],
        nutritionInfo: {
          calories: 120,
          protein: 2,
          carbs: 8,
          fat: 10,
          fiber: 4,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant4._id,
      },
      {
        name: "Payasam",
        description: "South Indian rice pudding",
        price: 5.99,
        image: "https://example.com/payasam.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: ["rice", "milk", "sugar", "cardamom", "nuts"],
        nutritionInfo: {
          calories: 280,
          protein: 6,
          carbs: 42,
          fat: 10,
          fiber: 2,
        },
        allergenInfo: ["dairy", "nuts"],
        restaurant: restaurant4._id,
      },
    ]);

    // Menu Items for Kolkata Kathi Roll
    await MenuItem.create([
      {
        name: "Egg Roll",
        description: "Paratha wrapped around egg and vegetables",
        price: 4.99,
        image: "https://example.com/eggroll.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "egg", "onion", "chili", "spices"],
        nutritionInfo: {
          calories: 380,
          protein: 14,
          carbs: 42,
          fat: 18,
          fiber: 4,
        },
        allergenInfo: ["gluten", "eggs"],
        popular: true,
        restaurant: restaurant5._id,
        reviews: [
          {
            user: "RollLover",
            rating: 5,
            comment: "Authentic Kolkata street-style egg roll!",
            date: new Date("2023-07-15"),
          },
        ],
      },
      {
        name: "Chicken Kathi Roll",
        description: "Tandoori chicken wrapped in paratha",
        price: 6.99,
        image: "https://example.com/chickenkathi.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "chicken", "onion", "egg", "spices"],
        nutritionInfo: {
          calories: 420,
          protein: 24,
          carbs: 38,
          fat: 20,
          fiber: 4,
        },
        allergenInfo: ["gluten", "eggs"],
        popular: true,
        restaurant: restaurant5._id,
      },
      {
        name: "Mutton Roll",
        description: "Spicy mutton wrapped in paratha",
        price: 7.99,
        image: "https://example.com/muttonroll.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "mutton", "onion", "spices"],
        nutritionInfo: {
          calories: 480,
          protein: 28,
          carbs: 40,
          fat: 24,
          fiber: 4,
        },
        allergenInfo: ["gluten"],
        restaurant: restaurant5._id,
      },
      {
        name: "Paneer Roll",
        description: "Spicy paneer wrapped in paratha",
        price: 5.99,
        image: "https://example.com/paneerroll.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["paratha", "paneer", "onion", "capsicum", "spices"],
        nutritionInfo: {
          calories: 400,
          protein: 16,
          carbs: 42,
          fat: 20,
          fiber: 6,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant5._id,
      },
      {
        name: "Double Egg Roll",
        description: "Double egg with extra spices in paratha",
        price: 5.99,
        image: "https://example.com/doubleegg.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "egg", "onion", "extra egg", "spices"],
        nutritionInfo: {
          calories: 480,
          protein: 22,
          carbs: 42,
          fat: 26,
          fiber: 4,
        },
        allergenInfo: ["gluten", "eggs"],
        restaurant: restaurant5._id,
      },
      {
        name: "Chicken Cheese Roll",
        description: "Chicken with melted cheese in paratha",
        price: 7.99,
        image: "https://example.com/chickencheese.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "chicken", "cheese", "onion", "spices"],
        nutritionInfo: {
          calories: 520,
          protein: 30,
          carbs: 38,
          fat: 30,
          fiber: 4,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant5._id,
      },
      {
        name: "Aloo Roll",
        description: "Spicy potato filling in paratha",
        price: 3.99,
        image: "https://example.com/alooroll.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: true,
        ingredients: ["paratha", "potato", "onion", "spices"],
        nutritionInfo: {
          calories: 340,
          protein: 6,
          carbs: 52,
          fat: 12,
          fiber: 6,
        },
        allergenInfo: ["gluten"],
        restaurant: restaurant5._id,
      },
      {
        name: "Chicken Tikka Roll",
        description: "Tandoori chicken tikka in paratha",
        price: 7.99,
        image: "https://example.com/chickentikka.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "chicken tikka", "onion", "mint chutney"],
        nutritionInfo: {
          calories: 440,
          protein: 32,
          carbs: 38,
          fat: 20,
          fiber: 4,
        },
        allergenInfo: ["gluten"],
        popular: true,
        restaurant: restaurant5._id,
      },
      {
        name: "Egg Chicken Roll",
        description: "Combination of egg and chicken in paratha",
        price: 6.99,
        image: "https://example.com/eggchicken.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "egg", "chicken", "onion", "spices"],
        nutritionInfo: {
          calories: 460,
          protein: 28,
          carbs: 38,
          fat: 24,
          fiber: 4,
        },
        allergenInfo: ["gluten", "eggs"],
        restaurant: restaurant5._id,
      },
      {
        name: "Mughlai Paratha",
        description: "Stuffed flatbread with egg and meat",
        price: 7.99,
        image: "https://example.com/mughlaiparatha.jpg",
        category: "main course",
        isVeg: false,
        isSpicy: true,
        ingredients: ["paratha", "egg", "chicken", "onion", "spices"],
        nutritionInfo: {
          calories: 520,
          protein: 32,
          carbs: 42,
          fat: 28,
          fiber: 4,
        },
        allergenInfo: ["gluten", "eggs"],
        restaurant: restaurant5._id,
      },
    ]);

    // Menu Items for Gujarat Thali
    await MenuItem.create([
      {
        name: "Unlimited Gujarati Thali",
        description: "Traditional meal with unlimited servings",
        price: 14.99,
        image: "https://example.com/gujaratithali.jpg",
        category: "thali",
        isVeg: true,
        isSpicy: false,
        ingredients: [
          "rotli",
          "dal",
          "kadhi",
          "shaak",
          "rice",
          "farsan",
          "sweet",
        ],
        nutritionInfo: {
          calories: 800,
          protein: 24,
          carbs: 120,
          fat: 25,
          fiber: 20,
        },
        allergenInfo: ["gluten", "dairy"],
        popular: true,
        restaurant: restaurant6._id,
        reviews: [
          {
            user: "ThaliExpert",
            rating: 5,
            comment:
              "Authentic Gujarati flavors with perfect balance of sweet and savory",
            date: new Date("2023-06-30"),
          },
        ],
      },
      {
        name: "Dal Dhokli",
        description: "Wheat dumplings in sweet-spicy lentil soup",
        price: 9.99,
        image: "https://example.com/daldhokli.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: false,
        ingredients: [
          "wheat flour",
          "tuvar dal",
          "jaggery",
          "peanuts",
          "spices",
        ],
        nutritionInfo: {
          calories: 380,
          protein: 14,
          carbs: 62,
          fat: 8,
          fiber: 12,
        },
        allergenInfo: ["gluten", "nuts"],
        restaurant: restaurant6._id,
      },
      {
        name: "Khandvi",
        description: "Gram flour rolls with tempered spices",
        price: 6.99,
        image: "https://example.com/khandvi.jpg",
        category: "appetizer",
        isVeg: true,
        isSpicy: false,
        ingredients: [
          "gram flour",
          "yogurt",
          "mustard seeds",
          "coconut",
          "coriander",
        ],
        nutritionInfo: {
          calories: 220,
          protein: 8,
          carbs: 32,
          fat: 6,
          fiber: 6,
        },
        allergenInfo: ["gluten-free", "dairy"],
        restaurant: restaurant6._id,
      },
      {
        name: "Undhiyu",
        description: "Seasonal vegetable medley cooked with spices",
        price: 10.99,
        image: "https://example.com/undhiyu.jpg",
        category: "main course",
        isVeg: true,
        isSpicy: false,
        ingredients: [
          "purple yam",
          "beans",
          "eggplant",
          "banana",
          "methi muthiya",
        ],
        nutritionInfo: {
          calories: 280,
          protein: 8,
          carbs: 48,
          fat: 8,
          fiber: 15,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant6._id,
      },
      {
        name: "Thepla",
        description: "Fenugreek flatbread",
        price: 4.99,
        image: "https://example.com/thepla.jpg",
        category: "bread",
        isVeg: true,
        isSpicy: false,
        ingredients: ["wheat flour", "fenugreek leaves", "yogurt", "spices"],
        nutritionInfo: {
          calories: 180,
          protein: 6,
          carbs: 32,
          fat: 4,
          fiber: 6,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant6._id,
      },
      {
        name: "Fafda",
        description: "Crispy gram flour snack",
        price: 5.99,
        image: "https://example.com/fafda.jpg",
        category: "snack",
        isVeg: true,
        isSpicy: false,
        ingredients: ["gram flour", "carom seeds", "oil", "salt"],
        nutritionInfo: {
          calories: 240,
          protein: 8,
          carbs: 32,
          fat: 10,
          fiber: 6,
        },
        allergenInfo: ["gluten-free"],
        restaurant: restaurant6._id,
      },
      {
        name: "Jalebi",
        description: "Crispy sweet spirals",
        price: 4.99,
        image: "https://example.com/jalebi.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: ["maida", "yogurt", "sugar syrup", "saffron"],
        nutritionInfo: {
          calories: 320,
          protein: 4,
          carbs: 68,
          fat: 6,
          fiber: 2,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant6._id,
      },
      {
        name: "Aamras Puri",
        description: "Mango pulp with fried bread",
        price: 8.99,
        image: "https://example.com/aamras.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: ["mango", "sugar", "wheat flour", "ghee"],
        nutritionInfo: {
          calories: 380,
          protein: 6,
          carbs: 72,
          fat: 10,
          fiber: 6,
        },
        allergenInfo: ["gluten", "dairy"],
        restaurant: restaurant6._id,
      },
      {
        name: "Shrikhand",
        description: "Sweet strained yogurt with nuts",
        price: 5.99,
        image: "https://example.com/shrikhand.jpg",
        category: "dessert",
        isVeg: true,
        ingredients: ["yogurt", "sugar", "cardamom", "pistachios"],
        nutritionInfo: {
          calories: 280,
          protein: 8,
          carbs: 42,
          fat: 10,
          fiber: 2,
        },
        allergenInfo: ["dairy", "nuts"],
        restaurant: restaurant6._id,
      },
      {
        name: "Masala Chaas",
        description: "Spiced buttermilk",
        price: 2.99,
        image: "https://example.com/chaas.jpg",
        category: "beverage",
        isVeg: true,
        ingredients: ["yogurt", "water", "cumin", "mint", "salt"],
        nutritionInfo: {
          calories: 60,
          protein: 4,
          carbs: 8,
          fat: 2,
          fiber: 0,
        },
        allergenInfo: ["dairy"],
        restaurant: restaurant6._id,
      },
    ]);

    console.log("Database seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
});
